### ISSUE TITLE
Add option to leave scrolling ticker stock

### ISSUE THREAD

**Issue by alan-morford** [orangeglo/gbnp#6]
Is there a way to leave the ticker text alone? I know the GB Memory Binary Maker leaves it alone. I'm hoping your web tool can have that option as well.

**Comment by epbarger** [comment]
Yup this should be possible. Because I'm supplying the menu file, it would use the original Japanese ticker from the dump of my original cart. Though maybe I can have it load the ticker text from an uploaded complete menu file - I'll have to see

**Comment by epbarger** [comment]
Added this option with https://github.com/orangeglo/gbnp/pull/7 . It will use the original ticker text from my menu ROM. I need to think more about how it would work if you could provide your own menu file, will open a separate issue for that
